version: "3.8"

services:
  db:
    image: postgres:14
    container_name: stocks_db
    restart: always
    environment:
      POSTGRES_USER: stocksim_user
      POSTGRES_PASSWORD: stocksim_pass
      POSTGRES_DB: stocksim
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Main RabbitMQ port
      - "15672:15672"   # Web UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data:
